
HOME_DIR = "/Users/junhalee/Desktop/perovskite-phase-pred/"
DATA_DIR = HOME_DIR + "data/"
DEVICE = "cpu"
SEED = 42

"""
List of reaction variables used for prediction.
    - key: name of the variable
    - val[0]: type of variable (continuous, discrete, or categorical)
    - val[1]: name of the variable
"""
RXN_VARS = {
            # "functional": ["categorical", "Functional"],
            # "denticity": ["discrete", "Denticity"],
            # "functional": ["discrete", "Functional group charge"],
            # "length": ["discrete", "Length"],
            # "total": ["discrete", "Total Charge"],
            # "zwitterion": ["categorical", "Zwitterion?"],
            # "mw": ["continuous", "MW"],
            # "consensus": ["continuous", "Consensus Log P"],
            # "synthetic": ["continuous", "Synthetic Accessibility"],
            "ie": ["continuous", "IE"],
            "amw": ["continuous", "AMW"],
            "frac_sp3": ["continuous", "frac_sp3"],
            "heavy_atom": ["discrete", "heavy_atom"],
            "nh_oh": ["discrete", "NH_OH"],
            "aromatic_heter": ["discrete", "aromatic_heter"],
            "aromatic_ring": ["discrete", "aromatic_ring"],
            "h_accept": ["discrete", "h_accept"],
            "h_donot": ["discrete", "h_donot"],
            "num_heteroatom": ["discrete", "num_heteroatom"],
            "num_rotable": ["discrete", "num_rotable"],
            "num_aliphatic": ["discrete", "num_aliphatic"],
            "aliphatic_heter": ["discrete", "aliphatic_heter"],
            "aromatic_c": ["discrete", "aromatic_C"],
            # "aliphatic_c": ["discrete", "aliphatic_C"],
            # "saturated_c": ["discrete", "saturated_C"],
            "saturated_heter": ["discrete", "saturated_heter"],
            "saturated_ring": ["discrete", "saturated_ring"],
            # "asphere": ["continuous", "asphere"],
            "max_partial_charge": ["continuous", "MaxPartialCharge"],
            "min_partial_charge": ["continuous", "MinPartialCharge"],
            "numvalence": ["discrete", "numvalence"],
            "numradical": ["discrete", "numradical"],
            # "radius_of_gyration": ["continuous", "RadiusOfGyration"],
            # "spherocity": ["continuous", "spherocity"],
            "halide": ["categorical", "Halide"],
            "ionic_radius": ["continuous", "Halide Ionic Radius"],
            "ionization_energy_halide": ["continuous", "Halide Ionization Energy (eV)"],
            "electron_affinity_halide": ["continuous", "Halide Electron Affinity (eV)"],
            "pearson_hardness_halide": ["continuous", "Halide Pearson Hardness (eV)"],
            "mulliken_electronegativity_halide": ["continuous", "Halide Mulliken Electronegativity (eV)"],
            "pauling_electronegativity_halide": ["continuous", "Halide Pauling Electronegativity (Neutral Atom)"],
            "number_of_electrons": ["discrete", "Number of Electrons"],
            "atomic_mass": ["continuous", "Atomic Mass"],
            # "charge": ["discrete", "Charge"],
            "ion": ["categorical", "Ion"],
            "ionization_energy_metal": ["continuous", "Metal Ionization Energy (kJ/mol)"],
            "electron_affinity_metal": ["continuous", "Metal Electron Affinity (kJ/mol)"],
            "pearson_hardness_metal": ["continuous", "Metal Pearson Hardness (eV)"],
            "mulliken_electronegativity_metal": ["continuous", "Metal Mulliken Electronegativity (eV; ionic)"],
            "pauling_electronegativity_metal": ["continuous", "Metal Pauling Electronegativity (atomic)"],
            "electrons": ["discrete", "No.Electrons"],
            "valence_d_electron_count": ["discrete", "Valence d electron count"],
            "ionic_radius": ["continuous", "Ionic Radius"]}


"""
Categorical mappings to an integer label for each categorical variable.
"""
CATEGORICAL_MAPPINGS = {"functional": {'Disulfide': 0,
                                       'Ether': 1,
                                       'Pyrazine': 2,
                                       'Pyrrolidine': 3,
                                       'alcohol': 4,
                                       'amide': 5,
                                       'boronic acid': 6,
                                       'carboxylic acid': 7,
                                       'diol': 8,
                                       'ester': 9,
                                       'ether': 10,
                                       'ether/alcohol': 11,
                                       'furan': 12,
                                       'imidazole': 13,
                                       'indole': 14,
                                       'ketone': 15,
                                       'morpholine': 16,
                                       'nitrile': 17,
                                       'organophosphate': 18,
                                       'organosulfate': 19,
                                       'oxazole*': 20,
                                       'phenol': 21,
                                       'piperidine/ketone': 22,
                                       'pyran': 16,
                                       'pyridine': 24,
                                       'pyrimidine': 25,
                                       'secondary amine': 26,
                                       'sulfide': 27,
                                       'sulfone': 28,
                                       'sulfonic acid': 29,
                                       'thiane': 30,
                                       'thiazole*': 31,
                                       'thiol': 32,
                                       'thiomorpholine': 30,
                                       'thiophene': 23},
                        "ion": {'Cu++': 0, 'Mn++': 1, 'Pb++': 2},
                        "halide": {'Br': 0, 'Cl': 1, 'I': 2},
                        "zwitterion": {0: 0, 1: 1}}
